name: CI/CD

on:
  push:
    branches-ignore:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches-ignore:
      - 'master'
  workflow_dispatch:
    inputs:
      action:
        description: '手动执行的操作 (test/deploy/none)'
        required: true
        default: 'none'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm i bun@1.2.17 -g && bun install

      - name: Get version from package.json
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Build project
        run: bun run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Release for master branch
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}

      - name: Release for other branches
        if: github.ref != 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Pre-Release ${{ github.ref_name }}
          prerelease: true
